name: 'snowflake_cert_ab'
version: '1.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project. Profiles contain
# database connection information, and should be configured in the  ~/.dbt/profiles.yml file
profile: 'snowflake_cert_ab'

target-path: "target"   # directory which will store compiled SQL files
log-path: "logs"        # directory which will store DBT logs

clean-targets:          # directories to be removed by `dbt clean`
    - "target"
    - "logs"

models:
  snowflake_cert_ab:
    +materialized: view
