version: 2
sources:
###################################################################################################
- name: ETL1
  database: AIRBYTE_DB
  tables:
###################################################################################################
  - name: tc9_src_lineitem_1
  - name: tc9_src_lineitem_2
  - name: tc9_src_lineitem_3
